security:
    encoders:
      App\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
          entity:
            class: App\Entity\User
            property: pseudo
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
              login_path: connexion
              check_path: connexion
            logout:
              path: deconnexion
              target: index

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profil, roles: IS_AUTHENTICATED_FULLY }
